### PR TITLE
Plugin optimizations

### PR DESCRIPTION
**Pull request by kasperisager**
Optimize Javascript and CSS and simplify adding the jump-to-top button

### CODE REVIEW

**Comment by hgtonight** [comment]
Is the throttle really necessary?

I like the idea of removing the module class and hiding the button by default.

**Comment by kasperisager** [comment]
The throttle isn't strictly necessary but improves performance on older systems

**Comment by hgtonight** [comment]
I was actually just reading up on it and think I want to use the debounce functionality instead of the throttling.

Thanks for the PR.

**Comment by kasperisager** [comment]
Okey dokey, that should be an easy change then – and you're most certainly welcome!

**Pull request merged**
